### PR TITLE
Support terminus 1.x

### LINKED ISSUE #22: Update caboose for Terminus 1.0
## Problem / motivation
Terminus 1.0 is out! It's the new hotness and fully supported by Pantheon.

Unfortunately, we have a lot of hard-coded commands in here that reference the 0.x terminus command syntax (e.g. `terminus auth login` vs. `terminus auth:login`.

## Proposed resolution
- Let's _not_ support two versions of terminus.
- Let's update all terminus commands to use the new 1.0 terminus command style.

Devs can update to the new version of caboose as they update their local version of terminus.

### PR DESCRIPTION
**Pull request by iamEAP**
Closes #22

### CODE REVIEW

**Comment by iamEAP** [comment]
@jribe If you want to test.

**Comment by jribe** [comment]
LGTM, but we aren't using a pinned version of caboose yet. That'll be going through this week. Please hold off on merging this until then because this will break our stuff that hasn't upgraded to terminus 1.0 yet.

**Comment by jribe** [comment]
https://github.com/tableau-mkt/tableau-public/pull/568 will add a pinned Caboose commit hash

**Comment by iamEAP** [comment]
Cool. Will hold off on merging.

**Comment by jribe** [comment]
tableau-public is now using a pinned version of caboose. We're good to go on this change

**Comment by jribe** [comment]
Probably want to update the README.md with terminus 1.0 as the minimum version and replace `terminus auth login` with `terminus auth:login`

**Comment by jribe** [comment]
I tried using this in my local setup and got hit by this:

```
+ drush caboose integration
  _     _   _       __             _
 | |___| |_( )___  / _|_ _ ___ ___| |_  ___ _ _    _  _ _ __
 | / -_)  _|/(_-< |  _| '_/ -_|_-<| ' \/ -_) ' \  | || | '_ \
 |_\___|\__| /__/ |_| |_| \___/__/|_||_\___|_||_|  \_,_| .__/
                                                       |_|
2017-01-31T22:17:20.417638709Z 
Invalid argument supplied for foreach() caboose.drush.inc:135          [warning]
No site UUID or name specified.                                          [error]
```

**Comment by iamEAP** [comment]
@jribe are you on `1.0.0`, or `1.0.0-beta.1`?

**Comment by jribe** [comment]
Terminus 1.0.0 and php 5.5

**Comment by iamEAP** [comment]
@jribe Not able to reproduce, but have a possible fix. Try now?

**Comment by jribe** [comment]
Same error, different line number now:

```
+ drush caboose integration
  _     _   _       __             _
 | |___| |_( )___  / _|_ _ ___ ___| |_  ___ _ _    _  _ _ __
 | / -_)  _|/(_-< |  _| '_/ -_|_-<| ' \/ -_) ' \  | || | '_ \
 |_\___|\__| /__/ |_| |_| \___/__/|_||_\___|_||_|  \_,_| .__/
                                                       |_|
2017-02-02T18:50:31.912229295Z 
Invalid argument supplied for foreach() caboose.drush.inc:140          [warning]
No site UUID or name specified.                                          [error]
```

**Comment by jribe** [comment]
step to repro a pretty simple, just checkout the `terminus-1-scripts` branch of tableau-public, run `npm run setup`, and you should get that error in the drupal container's logs (viewable via cli or Kitematic)

**Comment by iamEAP** [comment]
@jribe It's going to take me quite awhile to get that script to actually run. Do you get any output when you run `terminus site:list --format=json`?

**Comment by jribe** [comment]
```
+ cd /var/www/html
+ mkdir -p sites/default/files/tmp
+ dockerize -wait tcp://database:3306 -timeout 60s
2017/02/02 20:33:00 Waiting for host: tcp://database:3306
2017/02/02 20:33:00 Connected to tcp://database:3306
+ terminus auth:login --machine-token=REDACTED
 [notice] Logging in via machine token.
+ terminus site:list --format=json
2017-02-02T20:33:10.645906065Z 
Warning: Invalid argument supplied for foreach() in /root/.composer/global/pantheon-systems/terminus/vendor/pantheon-systems/terminus/src/Collections/Sites.php on line 80
{
    "9968833e-c25a-45f1-a6c2-d5bb9774cc01": {
        "name": "jribe-test",
        "id": "9968833e-c25a-45f1-a6c2-d5bb9774cc01",
        "service_level": "free",
        "framework": "drupal",
        "owner": "dc88475a-019b-4443-946b-878279167233",
        "created": "2016-06-27 18:59:30",
        "memberships": "dc88475a-019b-4443-946b-878279167233: Team",
        "frozen": "false"
    },
    "9e767cd7-1033-43a4-bbde-2b76f6c9014b": {
        "name": "tableau-public",
        "id": "9e767cd7-1033-43a4-bbde-2b76f6c9014b",
        "service_level": "elite",
        "framework": "drupal",
        "owner": "615277bd-b0fd-4e10-b5de-16136ffd8e8e",
        "created": "2014-07-15 22:19:40",
        "memberships": "dc88475a-019b-4443-946b-878279167233: Team",
        "frozen": "false"
    }
}
+ drush caboose integration
  _     _   _       __             _
 | |___| |_( )___  / _|_ _ ___ ___| |_  ___ _ _    _  _ _ __
 | / -_)  _|/(_-< |  _| '_/ -_|_-<| ' \/ -_) ' \  | || | '_ \
 |_\___|\__| /__/ |_| |_| \___/__/|_||_\___|_||_|  \_,_| .__/
                                                       |_|
Invalid argument supplied for foreach() caboose.drush.inc:140          [warning]
No site UUID or name specified.                                          [error]
```

**Comment by iamEAP** [comment]
Thanks @jribe. Looks like the problem is that terminus itself is printing warnings during command execution, which we're trying to parse along side the actual JSON output of the command.

^ Pushed an update that attempts to avoid capturing `stderr`.  Try now?

**Comment by jribe** [comment]
Looks like the warning is output to stdout. /facepalm

```
$ terminus site:list --format=json 2>/dev/null

Warning: Invalid argument supplied for foreach() in /usr/local/Cellar/terminus/1.0.0_1/src/Collections/Sites.php on line 80
{
    "9968833e-c25a-45f1-a6c2-d5bb9774cc01": {
        "name": "jribe-test",
        "id": "9968833e-c25a-45f1-a6c2-d5bb9774cc01",
        "service_level": "free",
        "framework": "drupal",
        "owner": "dc88475a-019b-4443-946b-878279167233",
        "created": "2016-06-27 18:59:30",
        "memberships": "dc88475a-019b-4443-946b-878279167233: Team",
        "frozen": "false"
    },
    "9e767cd7-1033-43a4-bbde-2b76f6c9014b": {
        "name": "tableau-public",
        "id": "9e767cd7-1033-43a4-bbde-2b76f6c9014b",
        "service_level": "elite",
        "framework": "drupal",
        "owner": "615277bd-b0fd-4e10-b5de-16136ffd8e8e",
        "created": "2014-07-15 22:19:40",
        "memberships": "dc88475a-019b-4443-946b-878279167233: Team",
        "frozen": "false"
    }
}
```

**Comment by jribe** [comment]
https://github.com/pantheon-systems/terminus/issues/1585

*sigh*

**Comment by jribe** [comment]
Do we wait for them to fix it or put in a workaround?

**Comment by iamEAP** [comment]
We could certainly regex the JSON out...  You might also be able to put something in a php.ini file that silences warnings/errors?

**Comment by jribe** [comment]
If you use the `--team` option on `terminus site:list`, it skips the code that creates the warning.

**Comment by iamEAP** [comment]
Not necessarily something we want to do–believe that would prevent folks on our side from caboose'ing sites they have access to through organization membership but not team membership.

**Comment by jribe** [comment]
Well, `terminus org:list` also explodes if you have no orgs. Could add the `--team` arg if that one exits with non-zero.

**Comment by iamEAP** [comment]
That seems reasonable.

**Comment by iamEAP** [comment]
@jribe ^

**Comment by jribe** [comment]
It worked! Hooray!

**Pull request merged**
